import GenBeauGrp.Abelian
import GenBeauGrp.Structures
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.ZMod.QuotientGroup

/-!
# The Beauville spectrum of `C_p²` for odd primes `p`

`CpSq p` is the elementary-abelian group of order `p²`, modelled as
`Multiplicative (ZMod p × ZMod p)`. For `p` prime its non-identity elements all have order `p`,
so its order-`p` subgroups are the "lines" of the `ZMod p`-plane.
-/

/-- The group `C_p²`, modelled multiplicatively as `Multiplicative (ZMod p × ZMod p)`. -/
abbrev CpSq (p : ℕ) := Multiplicative (ZMod p × ZMod p)

namespace CpSq

set_option linter.unusedSectionVars false

variable {p : ℕ} [Fact p.Prime]

instance : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩

/-- Every element of `C_p²` satisfies `g ^ p = 1` (the group has exponent `p`). -/
theorem pow_p_eq_one (g : CpSq p) : g ^ p = 1 := by
  have h : (p : ℕ) • (Multiplicative.toAdd g) = 0 := by ext <;> simp [nsmul_eq_mul]
  apply Multiplicative.toAdd.injective
  simpa [toAdd_pow] using h

/-- `C_p²` has order `p²`. -/
theorem card_eq : Nat.card (CpSq p) = p ^ 2 := by
  rw [Nat.card_congr Multiplicative.toAdd, Nat.card_prod, Nat.card_eq_fintype_card, ZMod.card,
    pow_two]

/-- Every non-identity element of `C_p²` has order `p`. -/
theorem orderOf_eq_p {g : CpSq p} (hg : g ≠ 1) : orderOf g = p := by
  have hp : p.Prime := Fact.out
  rcases (Nat.dvd_prime hp).1 (orderOf_dvd_of_pow_eq_one (pow_p_eq_one g)) with h | h
  · exact absurd (orderOf_eq_one_iff.1 h) hg
  · exact h

/-- The cyclic subgroup generated by a non-identity element of `C_p²` has order `p`. -/
theorem card_zpowers_eq_p {g : CpSq p} (hg : g ≠ 1) :
    Nat.card (Subgroup.zpowers g) = p := by
  rw [Nat.card_zpowers, orderOf_eq_p hg]

/-- An order-`p` subgroup of `C_p²` containing a non-identity element `g` is exactly `⟨g⟩`
(a "line" is determined by any of its non-identity points). -/
theorem zpowers_eq_of_mem {g : CpSq p} (hg : g ≠ 1) {H : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hmem : g ∈ H) : Subgroup.zpowers g = H := by
  apply Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hmem)
  rw [hH, card_zpowers_eq_p hg]

/-- Two order-`p` subgroups of `C_p²` sharing a non-identity element coincide. -/
theorem eq_of_mem_of_mem {g : CpSq p} (hg : g ≠ 1) {H K : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hK : Nat.card K = p) (hgH : g ∈ H) (hgK : g ∈ K) : H = K := by
  rw [← zpowers_eq_of_mem hg hH hgH, zpowers_eq_of_mem hg hK hgK]

/-- No single cyclic subgroup is all of `C_p²` (every element has order `< p²`). -/
theorem zpowers_ne_top (g : CpSq p) : Subgroup.zpowers g ≠ ⊤ := by
  intro h
  have hp : p.Prime := Fact.out
  have h1 : Nat.card (Subgroup.zpowers g) ≤ p := by
    rw [Nat.card_zpowers]
    exact Nat.le_of_dvd hp.pos (orderOf_dvd_of_pow_eq_one (pow_p_eq_one g))
  rw [h, Subgroup.card_top, card_eq] at h1
  have hle : p ≤ 1 := Nat.le_of_mul_le_mul_left (by rw [mul_one]; rwa [pow_two] at h1) hp.pos
  have := hp.two_le
  omega

/-! ### Generating-pair structure

For a generating pair `(x, y)` of `C_p²` the elements `x, y, x*y` are non-identity and the three
cyclic subgroups `⟨x⟩, ⟨y⟩, ⟨x*y⟩` are pairwise distinct. -/

/-- Any subgroup containing both members of a generating pair is the whole group. -/
theorem top_of_mem {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)
    {H : Subgroup (CpSq p)} (hx : x ∈ H) (hy : y ∈ H) : H = ⊤ := by
  have h1 : Subgroup.closure ({x, y} : Set (CpSq p)) ≤ H := by
    rw [Subgroup.closure_le, Set.insert_subset_iff, Set.singleton_subset_iff]
    exact ⟨hx, hy⟩
  rw [hgen] at h1
  exact top_le_iff.mp h1

variable {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)

include hgen

theorem fst_ne_one : x ≠ 1 := fun hx =>
  zpowers_ne_top y (top_of_mem hgen (hx ▸ one_mem _) (Subgroup.mem_zpowers y))

theorem snd_ne_one : y ≠ 1 := fun hy =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (hy ▸ one_mem _))

theorem mul_ne_one : x * y ≠ 1 := by
  intro hxy
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  rw [eq_inv_of_mul_eq_one_right hxy]
  exact inv_mem (Subgroup.mem_zpowers x)

theorem zpowers_fst_ne_snd : Subgroup.zpowers x ≠ Subgroup.zpowers y := fun h =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (h.symm ▸ Subgroup.mem_zpowers y))

theorem zpowers_fst_ne_mul : Subgroup.zpowers x ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers x := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  have := mul_mem (inv_mem (Subgroup.mem_zpowers x)) hxy_mem
  rwa [inv_mul_cancel_left] at this

theorem zpowers_snd_ne_mul : Subgroup.zpowers y ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers y := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top y (top_of_mem hgen ?_ (Subgroup.mem_zpowers y))
  have := mul_mem hxy_mem (inv_mem (Subgroup.mem_zpowers y))
  rwa [mul_inv_cancel_right] at this

/-! ### Lemma: every Σ-set of `C_p²` contains exactly three cyclic subgroups -/

/-- The order-`p` subgroups contained in `Σ(x, y)` are exactly `⟨x⟩, ⟨y⟩, ⟨x*y⟩`. -/
theorem lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}
      = {Subgroup.zpowers x, Subgroup.zpowers y, Subgroup.zpowers (x * y)} := by
  have hσ : sigmaSet x y =
      ↑(Subgroup.zpowers x) ∪ ↑(Subgroup.zpowers y) ∪ ↑(Subgroup.zpowers (x * y)) :=
    sigmaSet_of_comm x y
  have hcx : Nat.card (Subgroup.zpowers x) = p := card_zpowers_eq_p (fst_ne_one hgen)
  have hcy : Nat.card (Subgroup.zpowers y) = p := card_zpowers_eq_p (snd_ne_one hgen)
  have hcz : Nat.card (Subgroup.zpowers (x * y)) = p := card_zpowers_eq_p (mul_ne_one hgen)
  ext H
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨hcard, hsub⟩
    have hne : H ≠ ⊥ := by
      rw [← Subgroup.one_lt_card_iff_ne_bot, hcard]; exact (Fact.out : p.Prime).one_lt
    obtain ⟨g, hgH, hg1⟩ := (Subgroup.nontrivial_iff_exists_ne_one H).mp
      ((Subgroup.nontrivial_iff_ne_bot H).mpr hne)
    have hg_in : g ∈ sigmaSet x y := hsub hgH
    rw [hσ] at hg_in
    simp only [Set.mem_union, SetLike.mem_coe] at hg_in
    rcases hg_in with (hgx | hgy) | hgz
    · exact Or.inl (eq_of_mem_of_mem hg1 hcard hcx hgH hgx)
    · exact Or.inr (Or.inl (eq_of_mem_of_mem hg1 hcard hcy hgH hgy))
    · exact Or.inr (Or.inr (eq_of_mem_of_mem hg1 hcard hcz hgH hgz))
  · rintro (rfl | rfl | rfl)
    · exact ⟨hcx, by rw [hσ]; exact Set.subset_union_left.trans Set.subset_union_left⟩
    · exact ⟨hcy, by rw [hσ]; exact Set.subset_union_right.trans Set.subset_union_left⟩
    · exact ⟨hcz, by rw [hσ]; exact Set.subset_union_right⟩

/-- **Lemma.** Every Σ-set of a generating pair of `C_p²` contains exactly three cyclic
subgroups (the lines `⟨x⟩, ⟨y⟩, ⟨x*y⟩`). -/
theorem ncard_lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}.ncard = 3 := by
  rw [lines_of_sigmaSet hgen, Set.ncard_eq_three]
  exact ⟨_, _, _, zpowers_fst_ne_snd hgen, zpowers_fst_ne_mul hgen, zpowers_snd_ne_mul hgen, rfl⟩

end CpSq
