import GenBeauGrp.Abelian
import GenBeauGrp.Structures
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.ZMod.QuotientGroup

/-!
# The Beauville spectrum of `C_p²` for odd primes `p`

`CpSq p` is the elementary-abelian group of order `p²`, modelled as
`Multiplicative (ZMod p × ZMod p)`. For `p` prime its non-identity elements all have order `p`,
so its order-`p` subgroups are the "lines" of the `ZMod p`-plane.
-/

/-- The group `C_p²`, modelled multiplicatively as `Multiplicative (ZMod p × ZMod p)`. -/
abbrev CpSq (p : ℕ) := Multiplicative (ZMod p × ZMod p)

namespace CpSq

set_option linter.unusedSectionVars false

variable {p : ℕ} [Fact p.Prime]

instance : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩

/-- Every element of `C_p²` satisfies `g ^ p = 1` (the group has exponent `p`). -/
theorem pow_p_eq_one (g : CpSq p) : g ^ p = 1 := by
  have h : (p : ℕ) • (Multiplicative.toAdd g) = 0 := by ext <;> simp [nsmul_eq_mul]
  apply Multiplicative.toAdd.injective
  simpa [toAdd_pow] using h

/-- `C_p²` has order `p²`. -/
theorem card_eq : Nat.card (CpSq p) = p ^ 2 := by
  rw [Nat.card_congr Multiplicative.toAdd, Nat.card_prod, Nat.card_eq_fintype_card, ZMod.card,
    pow_two]

/-- Every non-identity element of `C_p²` has order `p`. -/
theorem orderOf_eq_p {g : CpSq p} (hg : g ≠ 1) : orderOf g = p := by
  have hp : p.Prime := Fact.out
  rcases (Nat.dvd_prime hp).1 (orderOf_dvd_of_pow_eq_one (pow_p_eq_one g)) with h | h
  · exact absurd (orderOf_eq_one_iff.1 h) hg
  · exact h

/-- The cyclic subgroup generated by a non-identity element of `C_p²` has order `p`. -/
theorem card_zpowers_eq_p {g : CpSq p} (hg : g ≠ 1) :
    Nat.card (Subgroup.zpowers g) = p := by
  rw [Nat.card_zpowers, orderOf_eq_p hg]

/-- An order-`p` subgroup of `C_p²` containing a non-identity element `g` is exactly `⟨g⟩`
(a "line" is determined by any of its non-identity points). -/
theorem zpowers_eq_of_mem {g : CpSq p} (hg : g ≠ 1) {H : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hmem : g ∈ H) : Subgroup.zpowers g = H := by
  apply Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hmem)
  rw [hH, card_zpowers_eq_p hg]

/-- Two order-`p` subgroups of `C_p²` sharing a non-identity element coincide. -/
theorem eq_of_mem_of_mem {g : CpSq p} (hg : g ≠ 1) {H K : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hK : Nat.card K = p) (hgH : g ∈ H) (hgK : g ∈ K) : H = K := by
  rw [← zpowers_eq_of_mem hg hH hgH, zpowers_eq_of_mem hg hK hgK]

/-- No single cyclic subgroup is all of `C_p²` (every element has order `< p²`). -/
theorem zpowers_ne_top (g : CpSq p) : Subgroup.zpowers g ≠ ⊤ := by
  intro h
  have hp : p.Prime := Fact.out
  have h1 : Nat.card (Subgroup.zpowers g) ≤ p := by
    rw [Nat.card_zpowers]
    exact Nat.le_of_dvd hp.pos (orderOf_dvd_of_pow_eq_one (pow_p_eq_one g))
  rw [h, Subgroup.card_top, card_eq] at h1
  have hle : p ≤ 1 := Nat.le_of_mul_le_mul_left (by rw [mul_one]; rwa [pow_two] at h1) hp.pos
  have := hp.two_le
  omega

/-! ### Generating-pair structure

For a generating pair `(x, y)` of `C_p²` the elements `x, y, x*y` are non-identity and the three
cyclic subgroups `⟨x⟩, ⟨y⟩, ⟨x*y⟩` are pairwise distinct. -/

/-- Any subgroup containing both members of a generating pair is the whole group. -/
theorem top_of_mem {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)
    {H : Subgroup (CpSq p)} (hx : x ∈ H) (hy : y ∈ H) : H = ⊤ := by
  have h1 : Subgroup.closure ({x, y} : Set (CpSq p)) ≤ H := by
    rw [Subgroup.closure_le, Set.insert_subset_iff, Set.singleton_subset_iff]
    exact ⟨hx, hy⟩
  rw [hgen] at h1
  exact top_le_iff.mp h1

section GeneratingPair

variable {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)

include hgen

theorem fst_ne_one : x ≠ 1 := fun hx =>
  zpowers_ne_top y (top_of_mem hgen (hx ▸ one_mem _) (Subgroup.mem_zpowers y))

theorem snd_ne_one : y ≠ 1 := fun hy =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (hy ▸ one_mem _))

theorem mul_ne_one : x * y ≠ 1 := by
  intro hxy
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  rw [eq_inv_of_mul_eq_one_right hxy]
  exact inv_mem (Subgroup.mem_zpowers x)

theorem zpowers_fst_ne_snd : Subgroup.zpowers x ≠ Subgroup.zpowers y := fun h =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (h.symm ▸ Subgroup.mem_zpowers y))

theorem zpowers_fst_ne_mul : Subgroup.zpowers x ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers x := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  have := mul_mem (inv_mem (Subgroup.mem_zpowers x)) hxy_mem
  rwa [inv_mul_cancel_left] at this

theorem zpowers_snd_ne_mul : Subgroup.zpowers y ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers y := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top y (top_of_mem hgen ?_ (Subgroup.mem_zpowers y))
  have := mul_mem hxy_mem (inv_mem (Subgroup.mem_zpowers y))
  rwa [mul_inv_cancel_right] at this

/-! ### Lemma: every Σ-set of `C_p²` contains exactly three cyclic subgroups -/

/-- The order-`p` subgroups contained in `Σ(x, y)` are exactly `⟨x⟩, ⟨y⟩, ⟨x*y⟩`. -/
theorem lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}
      = {Subgroup.zpowers x, Subgroup.zpowers y, Subgroup.zpowers (x * y)} := by
  have hσ : sigmaSet x y =
      ↑(Subgroup.zpowers x) ∪ ↑(Subgroup.zpowers y) ∪ ↑(Subgroup.zpowers (x * y)) :=
    sigmaSet_of_comm x y
  have hcx : Nat.card (Subgroup.zpowers x) = p := card_zpowers_eq_p (fst_ne_one hgen)
  have hcy : Nat.card (Subgroup.zpowers y) = p := card_zpowers_eq_p (snd_ne_one hgen)
  have hcz : Nat.card (Subgroup.zpowers (x * y)) = p := card_zpowers_eq_p (mul_ne_one hgen)
  ext H
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨hcard, hsub⟩
    have hne : H ≠ ⊥ := by
      rw [← Subgroup.one_lt_card_iff_ne_bot, hcard]; exact (Fact.out : p.Prime).one_lt
    obtain ⟨g, hgH, hg1⟩ := (Subgroup.nontrivial_iff_exists_ne_one H).mp
      ((Subgroup.nontrivial_iff_ne_bot H).mpr hne)
    have hg_in : g ∈ sigmaSet x y := hsub hgH
    rw [hσ] at hg_in
    simp only [Set.mem_union, SetLike.mem_coe] at hg_in
    rcases hg_in with (hgx | hgy) | hgz
    · exact Or.inl (eq_of_mem_of_mem hg1 hcard hcx hgH hgx)
    · exact Or.inr (Or.inl (eq_of_mem_of_mem hg1 hcard hcy hgH hgy))
    · exact Or.inr (Or.inr (eq_of_mem_of_mem hg1 hcard hcz hgH hgz))
  · rintro (rfl | rfl | rfl)
    · exact ⟨hcx, by rw [hσ]; exact Set.subset_union_left.trans Set.subset_union_left⟩
    · exact ⟨hcy, by rw [hσ]; exact Set.subset_union_right.trans Set.subset_union_left⟩
    · exact ⟨hcz, by rw [hσ]; exact Set.subset_union_right⟩

/-- **Lemma.** Every Σ-set of a generating pair of `C_p²` contains exactly three cyclic
subgroups (the lines `⟨x⟩, ⟨y⟩, ⟨x*y⟩`). -/
theorem ncard_lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}.ncard = 3 := by
  rw [lines_of_sigmaSet hgen, Set.ncard_eq_three]
  exact ⟨_, _, _, zpowers_fst_ne_snd hgen, zpowers_fst_ne_mul hgen, zpowers_snd_ne_mul hgen, rfl⟩

end GeneratingPair

/-! ### Proposition: `max BSpec(C_p²) = 4` -/

/-- **Upper bound.** Any primitive generalised Beauville structure of `C_p²` has dimension `≤ 4`.
For each index `j`, primitivity yields a non-identity `g j` lying in every Σ-set except the `j`-th;
the lines `⟨g j⟩` are distinct and, for a fixed `i`, the `d-1` of them with `j ≠ i` all lie inside
`Σ_i`, which holds only three lines. -/
theorem dimension_le_four (B : GeneralisedBeauvilleStructure (CpSq p))
    (hB : B.IsPrimitive) : B.dimension ≤ 4 := by
  classical
  have witness : ∀ j : B.ι, ∃ g : CpSq p, g ≠ 1 ∧
      (∀ k, k ≠ j → g ∈ sigmaSet (B.pairs k).x (B.pairs k).y) ∧
      g ∉ sigmaSet (B.pairs j).x (B.pairs j).y := by
    intro j
    have hproper : (Finset.univ.erase j) ≠ (Finset.univ : Finset B.ι) := by
      intro h
      have hj : j ∈ Finset.univ.erase j := by rw [h]; exact Finset.mem_univ j
      exact (Finset.mem_erase.mp hj).1 rfl
    have hne := hB _ hproper
    have h1mem : (1 : CpSq p) ∈
        ⋂ i ∈ Finset.univ.erase j, sigmaSet (B.pairs i).x (B.pairs i).y := by
      rw [Set.mem_iInter₂]; exact fun i _ => one_mem_sigmaSet _ _
    have hex : ∃ g ∈ (⋂ i ∈ Finset.univ.erase j, sigmaSet (B.pairs i).x (B.pairs i).y),
        g ≠ 1 := by
      by_contra hc
      simp only [not_exists, not_and, not_ne_iff] at hc
      exact hne (Set.eq_singleton_iff_unique_mem.mpr ⟨h1mem, hc⟩)
    obtain ⟨g, hgX, hg1⟩ := hex
    rw [Set.mem_iInter₂] at hgX
    refine ⟨g, hg1, fun k hk => hgX k (Finset.mem_erase.mpr ⟨hk, Finset.mem_univ k⟩), ?_⟩
    intro hgj
    have hall : g ∈ ⋂ i, sigmaSet (B.pairs i).x (B.pairs i).y := by
      rw [Set.mem_iInter]; intro k
      by_cases hk : k = j
      · subst hk; exact hgj
      · exact hgX k (Finset.mem_erase.mpr ⟨hk, Finset.mem_univ k⟩)
    rw [B.inter_sigmaSet_eq_one, Set.mem_singleton_iff] at hall
    exact hg1 hall
  choose g hg1 hgmem hgnot using witness
  set f : B.ι → Subgroup (CpSq p) := fun j => Subgroup.zpowers (g j) with hf
  rw [GeneralisedBeauvilleStructure.dimension]
  rcases isEmpty_or_nonempty B.ι with hempty | hne
  · have : Fintype.card B.ι = 0 := Fintype.card_eq_zero
    omega
  · obtain ⟨i⟩ := hne
    have hgen_i : Subgroup.closure ({(B.pairs i).x, (B.pairs i).y} : Set (CpSq p)) = ⊤ :=
      (B.pairs i).generates
    have hmaps : ∀ j ∈ Finset.univ.erase i,
        f j ∈ ({Subgroup.zpowers (B.pairs i).x, Subgroup.zpowers (B.pairs i).y,
          Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p))) := by
      intro j hj
      have hji : j ≠ i := (Finset.mem_erase.mp hj).1
      have hmem : g j ∈ sigmaSet (B.pairs i).x (B.pairs i).y := hgmem j i (Ne.symm hji)
      have hin : f j ∈ {H : Subgroup (CpSq p) | Nat.card H = p ∧
          (↑H : Set (CpSq p)) ⊆ sigmaSet (B.pairs i).x (B.pairs i).y} :=
        ⟨card_zpowers_eq_p (hg1 j), zpowers_subset_sigmaSet hmem⟩
      rw [lines_of_sigmaSet hgen_i] at hin
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hin
      simp only [Finset.mem_insert, Finset.mem_singleton]
      exact hin
    have hinj : Set.InjOn f ↑(Finset.univ.erase i) := by
      intro j _ j' _ hff
      by_contra hjj
      have hmem' : g j' ∈ sigmaSet (B.pairs j).x (B.pairs j).y := hgmem j' j hjj
      have hsub := zpowers_subset_sigmaSet hmem'
      have hgj_in : g j ∈ (↑(f j') : Set (CpSq p)) := by
        rw [← hff]; exact Subgroup.mem_zpowers (g j)
      exact hgnot j (hsub hgj_in)
    have hcard_le := Finset.card_le_card_of_injOn f
      (fun j hj => Finset.mem_coe.mpr (hmaps j (Finset.mem_coe.mp hj))) hinj
    have h3 : ({Subgroup.zpowers (B.pairs i).x, Subgroup.zpowers (B.pairs i).y,
        Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} :
          Finset (Subgroup (CpSq p))).card ≤ 3 := by
      have e1 := Finset.card_insert_le (Subgroup.zpowers (B.pairs i).x)
        ({Subgroup.zpowers (B.pairs i).y,
          Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p)))
      have e2 := Finset.card_insert_le (Subgroup.zpowers (B.pairs i).y)
        ({Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p)))
      simp only [Finset.card_singleton] at e2
      omega
    have hcard_erase : (Finset.univ.erase i).card = Fintype.card B.ι - 1 := by
      rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ]
    omega

/-! ### Construction helpers for the lower bound -/

/-- A linear functional separating `x` from `y` certifies `y ∉ ⟨x⟩`. -/
theorem not_mem_zpowers_of_hom {x y : CpSq p} (ℓ : (ZMod p × ZMod p) →+ ZMod p)
    (hx : ℓ (Multiplicative.toAdd x) = 0) (hy : ℓ (Multiplicative.toAdd y) ≠ 0) :
    y ∉ Subgroup.zpowers x := by
  intro hmem
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
  apply hy
  rw [← hk, toAdd_zpow, map_zsmul, hx, smul_zero]

/-- Two distinct lines span `C_p²`: if `x ≠ 1` and `y ∉ ⟨x⟩` then `x, y` generate. -/
theorem closure_eq_top {x y : CpSq p} (hx : x ≠ 1) (hy : y ∉ Subgroup.zpowers x) :
    Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤ := by
  set H := Subgroup.closure ({x, y} : Set (CpSq p)) with hHdef
  have hxH : x ∈ H := Subgroup.subset_closure (Set.mem_insert _ _)
  have hyH : y ∈ H := Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  have hxle : Subgroup.zpowers x ≤ H := Subgroup.zpowers_le.mpr hxH
  have hp : p.Prime := Fact.out
  have hdvd : Nat.card H ∣ p ^ 2 := by
    have := Subgroup.card_subgroup_dvd_card H; rwa [card_eq] at this
  have hpdvd : p ∣ Nat.card H := by
    have := Subgroup.card_dvd_of_le hxle; rwa [card_zpowers_eq_p hx] at this
  by_cases hc : Nat.card H = p
  · exfalso; apply hy; rw [zpowers_eq_of_mem hx hc hxH]; exact hyH
  · obtain ⟨k, hk2, hkeq⟩ := (Nat.dvd_prime_pow hp).mp hdvd
    have hk0 : k ≠ 0 := by
      rintro rfl; rw [pow_zero] at hkeq; rw [hkeq] at hpdvd
      exact (hp.one_lt.ne') (Nat.dvd_one.mp hpdvd)
    have hkne1 : k ≠ 1 := fun h => hc (by rw [hkeq, h, pow_one])
    have hk : k = 2 := by omega
    apply Subgroup.eq_top_of_card_eq
    rw [hkeq, hk, card_eq]

/-- For odd `p`, squaring a non-identity element keeps the same line. -/
theorem zpowers_sq {x : CpSq p} (hx : x ≠ 1) (hp2 : p ≠ 2) :
    Subgroup.zpowers (x ^ 2) = Subgroup.zpowers x := by
  have hx2 : x ^ 2 ≠ 1 := by
    intro h
    have hd : orderOf x ∣ 2 := orderOf_dvd_of_pow_eq_one h
    rw [orderOf_eq_p hx] at hd
    rcases Nat.prime_two.eq_one_or_self_of_dvd p hd with h1 | h2
    · exact (Fact.out : p.Prime).ne_one h1
    · exact hp2 h2
  exact zpowers_eq_of_mem hx2 (card_zpowers_eq_p hx) (pow_mem (Subgroup.mem_zpowers x) 2)

end CpSq
