import GenBeauGrp.Abelian
import GenBeauGrp.Structures
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Tactic.Abel

/-!
# The Beauville spectrum of `C_p²` for odd primes `p`

`CpSq p` is the elementary-abelian group of order `p²`, modelled as
`Multiplicative (ZMod p × ZMod p)`. For `p` prime its non-identity elements all have order `p`,
so its order-`p` subgroups are the "lines" of the `ZMod p`-plane.
-/

/-- The group `C_p²`, modelled multiplicatively as `Multiplicative (ZMod p × ZMod p)`. -/
abbrev CpSq (p : ℕ) := Multiplicative (ZMod p × ZMod p)

namespace CpSq

variable {p : ℕ} [Fact p.Prime]

instance : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩

/-- Every element of `C_n²` satisfies `g ^ n = 1` (the group has exponent `n`). -/
theorem pow_eq_one {n : ℕ} (g : CpSq n) : g ^ n = 1 := by
  have h : (n : ℕ) • (Multiplicative.toAdd g) = 0 := by ext <;> simp [nsmul_eq_mul]
  apply Multiplicative.toAdd.injective
  simpa [toAdd_pow] using h

/-- `C_p²` has order `p²`. -/
theorem card_eq : Nat.card (CpSq p) = p ^ 2 := by
  rw [Nat.card_congr Multiplicative.toAdd, Nat.card_prod, Nat.card_eq_fintype_card, ZMod.card,
    pow_two]

/-- Every non-identity element of `C_p²` has order `p`. -/
theorem orderOf_eq_p {g : CpSq p} (hg : g ≠ 1) : orderOf g = p := by
  have hp : p.Prime := Fact.out
  rcases (Nat.dvd_prime hp).1 (orderOf_dvd_of_pow_eq_one (pow_eq_one g)) with h | h
  · exact absurd (orderOf_eq_one_iff.1 h) hg
  · exact h

/-- The cyclic subgroup generated by a non-identity element of `C_p²` has order `p`. -/
theorem card_zpowers_eq_p {g : CpSq p} (hg : g ≠ 1) :
    Nat.card (Subgroup.zpowers g) = p := by
  rw [Nat.card_zpowers, orderOf_eq_p hg]

/-- An order-`p` subgroup of `C_p²` containing a non-identity element `g` is exactly `⟨g⟩`
(a "line" is determined by any of its non-identity points). -/
theorem zpowers_eq_of_mem {g : CpSq p} (hg : g ≠ 1) {H : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hmem : g ∈ H) : Subgroup.zpowers g = H := by
  apply Subgroup.eq_of_le_of_card_ge (Subgroup.zpowers_le.mpr hmem)
  rw [hH, card_zpowers_eq_p hg]

/-- Two order-`p` subgroups of `C_p²` sharing a non-identity element coincide. -/
theorem eq_of_mem_of_mem {g : CpSq p} (hg : g ≠ 1) {H K : Subgroup (CpSq p)}
    (hH : Nat.card H = p) (hK : Nat.card K = p) (hgH : g ∈ H) (hgK : g ∈ K) : H = K := by
  rw [← zpowers_eq_of_mem hg hH hgH, zpowers_eq_of_mem hg hK hgK]

/-- No single cyclic subgroup is all of `C_p²` (every element has order `< p²`). -/
theorem zpowers_ne_top (g : CpSq p) : Subgroup.zpowers g ≠ ⊤ := by
  intro h
  have hp : p.Prime := Fact.out
  have h1 : Nat.card (Subgroup.zpowers g) ≤ p := by
    rw [Nat.card_zpowers]
    exact Nat.le_of_dvd hp.pos (orderOf_dvd_of_pow_eq_one (pow_eq_one g))
  rw [h, Subgroup.card_top, card_eq] at h1
  have hle : p ≤ 1 := Nat.le_of_mul_le_mul_left (by rw [mul_one]; rwa [pow_two] at h1) hp.pos
  have := hp.two_le
  omega

/-! ### Generating-pair structure

For a generating pair `(x, y)` of `C_p²` the elements `x, y, x*y` are non-identity and the three
cyclic subgroups `⟨x⟩, ⟨y⟩, ⟨x*y⟩` are pairwise distinct. -/

/-- Any subgroup containing both members of a generating pair is the whole group. -/
theorem top_of_mem {G : Type*} [Group G] {x y : G} (hgen : Subgroup.closure ({x, y} : Set G) = ⊤)
    {H : Subgroup G} (hx : x ∈ H) (hy : y ∈ H) : H = ⊤ := by
  have h1 : Subgroup.closure ({x, y} : Set G) ≤ H := by
    rw [Subgroup.closure_le, Set.insert_subset_iff, Set.singleton_subset_iff]
    exact ⟨hx, hy⟩
  rw [hgen] at h1
  exact top_le_iff.mp h1

section GeneratingPair

variable {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)

include hgen

theorem fst_ne_one : x ≠ 1 := fun hx =>
  zpowers_ne_top y (top_of_mem hgen (hx ▸ one_mem _) (Subgroup.mem_zpowers y))

theorem snd_ne_one : y ≠ 1 := fun hy =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (hy ▸ one_mem _))

theorem mul_ne_one : x * y ≠ 1 := by
  intro hxy
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  rw [eq_inv_of_mul_eq_one_right hxy]
  exact inv_mem (Subgroup.mem_zpowers x)

theorem zpowers_fst_ne_snd : Subgroup.zpowers x ≠ Subgroup.zpowers y := fun h =>
  zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) (h.symm ▸ Subgroup.mem_zpowers y))

theorem zpowers_fst_ne_mul : Subgroup.zpowers x ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers x := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top x (top_of_mem hgen (Subgroup.mem_zpowers x) ?_)
  have := mul_mem (inv_mem (Subgroup.mem_zpowers x)) hxy_mem
  rwa [inv_mul_cancel_left] at this

theorem zpowers_snd_ne_mul : Subgroup.zpowers y ≠ Subgroup.zpowers (x * y) := by
  intro h
  have hxy_mem : x * y ∈ Subgroup.zpowers y := h.symm ▸ Subgroup.mem_zpowers (x * y)
  refine zpowers_ne_top y (top_of_mem hgen ?_ (Subgroup.mem_zpowers y))
  have := mul_mem hxy_mem (inv_mem (Subgroup.mem_zpowers y))
  rwa [mul_inv_cancel_right] at this

/-! ### Lemma: every Σ-set of `C_p²` contains exactly three cyclic subgroups -/

/-- The order-`p` subgroups contained in `Σ(x, y)` are exactly `⟨x⟩, ⟨y⟩, ⟨x*y⟩`. -/
theorem lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}
      = {Subgroup.zpowers x, Subgroup.zpowers y, Subgroup.zpowers (x * y)} := by
  have hσ : sigmaSet x y =
      ↑(Subgroup.zpowers x) ∪ ↑(Subgroup.zpowers y) ∪ ↑(Subgroup.zpowers (x * y)) :=
    sigmaSet_of_comm x y
  have hcx : Nat.card (Subgroup.zpowers x) = p := card_zpowers_eq_p (fst_ne_one hgen)
  have hcy : Nat.card (Subgroup.zpowers y) = p := card_zpowers_eq_p (snd_ne_one hgen)
  have hcz : Nat.card (Subgroup.zpowers (x * y)) = p := card_zpowers_eq_p (mul_ne_one hgen)
  ext H
  simp only [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨hcard, hsub⟩
    have hne : H ≠ ⊥ := by
      rw [← Subgroup.one_lt_card_iff_ne_bot, hcard]; exact (Fact.out : p.Prime).one_lt
    obtain ⟨g, hgH, hg1⟩ := (Subgroup.nontrivial_iff_exists_ne_one H).mp
      ((Subgroup.nontrivial_iff_ne_bot H).mpr hne)
    have hg_in : g ∈ sigmaSet x y := hsub hgH
    rw [hσ] at hg_in
    simp only [Set.mem_union, SetLike.mem_coe] at hg_in
    rcases hg_in with (hgx | hgy) | hgz
    · exact Or.inl (eq_of_mem_of_mem hg1 hcard hcx hgH hgx)
    · exact Or.inr (Or.inl (eq_of_mem_of_mem hg1 hcard hcy hgH hgy))
    · exact Or.inr (Or.inr (eq_of_mem_of_mem hg1 hcard hcz hgH hgz))
  · rintro (rfl | rfl | rfl)
    · exact ⟨hcx, by rw [hσ]; exact Set.subset_union_left.trans Set.subset_union_left⟩
    · exact ⟨hcy, by rw [hσ]; exact Set.subset_union_right.trans Set.subset_union_left⟩
    · exact ⟨hcz, by rw [hσ]; exact Set.subset_union_right⟩

/-- **Lemma.** Every Σ-set of a generating pair of `C_p²` contains exactly three cyclic
subgroups (the lines `⟨x⟩, ⟨y⟩, ⟨x*y⟩`). -/
theorem ncard_lines_of_sigmaSet :
    {H : Subgroup (CpSq p) | Nat.card H = p ∧ (↑H : Set (CpSq p)) ⊆ sigmaSet x y}.ncard = 3 := by
  rw [lines_of_sigmaSet hgen, Set.ncard_eq_three]
  exact ⟨_, _, _, zpowers_fst_ne_snd hgen, zpowers_fst_ne_mul hgen, zpowers_snd_ne_mul hgen, rfl⟩

end GeneratingPair

/-! ### Proposition: `max BSpec(C_p²) = 4` -/

/-- **Upper bound.** Any primitive generalised Beauville structure of `C_p²` has dimension `≤ 4`.
For each index `j`, primitivity yields a non-identity `g j` lying in every Σ-set except the `j`-th;
the lines `⟨g j⟩` are distinct and, for a fixed `i`, the `d-1` of them with `j ≠ i` all lie inside
`Σ_i`, which holds only three lines. -/
theorem dimension_le_four (B : GeneralisedBeauvilleStructure (CpSq p))
    (hB : B.IsPrimitive) : B.dimension ≤ 4 := by
  classical
  have witness : ∀ j : B.ι, ∃ g : CpSq p, g ≠ 1 ∧
      (∀ k, k ≠ j → g ∈ sigmaSet (B.pairs k).x (B.pairs k).y) ∧
      g ∉ sigmaSet (B.pairs j).x (B.pairs j).y := by
    intro j
    have hproper : (Finset.univ.erase j) ≠ (Finset.univ : Finset B.ι) := by
      intro h
      have hj : j ∈ Finset.univ.erase j := by rw [h]; exact Finset.mem_univ j
      exact (Finset.mem_erase.mp hj).1 rfl
    have hne := hB _ hproper
    have h1mem : (1 : CpSq p) ∈
        ⋂ i ∈ Finset.univ.erase j, sigmaSet (B.pairs i).x (B.pairs i).y := by
      rw [Set.mem_iInter₂]; exact fun i _ => one_mem_sigmaSet _ _
    have hex : ∃ g ∈ (⋂ i ∈ Finset.univ.erase j, sigmaSet (B.pairs i).x (B.pairs i).y),
        g ≠ 1 := by
      by_contra hc
      simp only [not_exists, not_and, not_ne_iff] at hc
      exact hne (Set.eq_singleton_iff_unique_mem.mpr ⟨h1mem, hc⟩)
    obtain ⟨g, hgX, hg1⟩ := hex
    rw [Set.mem_iInter₂] at hgX
    refine ⟨g, hg1, fun k hk => hgX k (Finset.mem_erase.mpr ⟨hk, Finset.mem_univ k⟩), ?_⟩
    intro hgj
    have hall : g ∈ ⋂ i, sigmaSet (B.pairs i).x (B.pairs i).y := by
      rw [Set.mem_iInter]; intro k
      by_cases hk : k = j
      · subst hk; exact hgj
      · exact hgX k (Finset.mem_erase.mpr ⟨hk, Finset.mem_univ k⟩)
    rw [B.inter_sigmaSet_eq_one, Set.mem_singleton_iff] at hall
    exact hg1 hall
  choose g hg1 hgmem hgnot using witness
  set f : B.ι → Subgroup (CpSq p) := fun j => Subgroup.zpowers (g j) with hf
  rw [GeneralisedBeauvilleStructure.dimension]
  rcases isEmpty_or_nonempty B.ι with hempty | hne
  · have : Fintype.card B.ι = 0 := Fintype.card_eq_zero
    omega
  · obtain ⟨i⟩ := hne
    have hgen_i : Subgroup.closure ({(B.pairs i).x, (B.pairs i).y} : Set (CpSq p)) = ⊤ :=
      (B.pairs i).generates
    have hmaps : ∀ j ∈ Finset.univ.erase i,
        f j ∈ ({Subgroup.zpowers (B.pairs i).x, Subgroup.zpowers (B.pairs i).y,
          Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p))) := by
      intro j hj
      have hji : j ≠ i := (Finset.mem_erase.mp hj).1
      have hmem : g j ∈ sigmaSet (B.pairs i).x (B.pairs i).y := hgmem j i (Ne.symm hji)
      have hin : f j ∈ {H : Subgroup (CpSq p) | Nat.card H = p ∧
          (↑H : Set (CpSq p)) ⊆ sigmaSet (B.pairs i).x (B.pairs i).y} :=
        ⟨card_zpowers_eq_p (hg1 j), zpowers_subset_sigmaSet hmem⟩
      rw [lines_of_sigmaSet hgen_i] at hin
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hin
      simp only [Finset.mem_insert, Finset.mem_singleton]
      exact hin
    have hinj : Set.InjOn f ↑(Finset.univ.erase i) := by
      intro j _ j' _ hff
      by_contra hjj
      have hmem' : g j' ∈ sigmaSet (B.pairs j).x (B.pairs j).y := hgmem j' j hjj
      have hsub := zpowers_subset_sigmaSet hmem'
      have hgj_in : g j ∈ (↑(f j') : Set (CpSq p)) := by
        rw [← hff]; exact Subgroup.mem_zpowers (g j)
      exact hgnot j (hsub hgj_in)
    have hcard_le := Finset.card_le_card_of_injOn f
      (fun j hj => Finset.mem_coe.mpr (hmaps j (Finset.mem_coe.mp hj))) hinj
    have h3 : ({Subgroup.zpowers (B.pairs i).x, Subgroup.zpowers (B.pairs i).y,
        Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} :
          Finset (Subgroup (CpSq p))).card ≤ 3 := by
      have e1 := Finset.card_insert_le (Subgroup.zpowers (B.pairs i).x)
        ({Subgroup.zpowers (B.pairs i).y,
          Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p)))
      have e2 := Finset.card_insert_le (Subgroup.zpowers (B.pairs i).y)
        ({Subgroup.zpowers ((B.pairs i).x * (B.pairs i).y)} : Finset (Subgroup (CpSq p)))
      simp only [Finset.card_singleton] at e2
      omega
    have hcard_erase : (Finset.univ.erase i).card = Fintype.card B.ι - 1 := by
      rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ]
    omega

/-! ### Construction helpers for the lower bound -/

/-- A linear functional separating `x` from `y` certifies `y ∉ ⟨x⟩`. -/
theorem not_mem_zpowers_of_hom {n : ℕ} {x y : CpSq n} (ℓ : (ZMod n × ZMod n) →+ ZMod n)
    (hx : ℓ (Multiplicative.toAdd x) = 0) (hy : ℓ (Multiplicative.toAdd y) ≠ 0) :
    y ∉ Subgroup.zpowers x := by
  intro hmem
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
  apply hy
  rw [← hk, toAdd_zpow, map_zsmul, hx, smul_zero]

/-- Two distinct lines span `C_p²`: if `x ≠ 1` and `y ∉ ⟨x⟩` then `x, y` generate. -/
theorem closure_eq_top {x y : CpSq p} (hx : x ≠ 1) (hy : y ∉ Subgroup.zpowers x) :
    Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤ := by
  set H := Subgroup.closure ({x, y} : Set (CpSq p)) with hHdef
  have hxH : x ∈ H := Subgroup.subset_closure (Set.mem_insert _ _)
  have hyH : y ∈ H := Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  have hxle : Subgroup.zpowers x ≤ H := Subgroup.zpowers_le.mpr hxH
  have hp : p.Prime := Fact.out
  have hdvd : Nat.card H ∣ p ^ 2 := by
    have := Subgroup.card_subgroup_dvd_card H; rwa [card_eq] at this
  have hpdvd : p ∣ Nat.card H := by
    have := Subgroup.card_dvd_of_le hxle; rwa [card_zpowers_eq_p hx] at this
  by_cases hc : Nat.card H = p
  · exfalso; apply hy; rw [zpowers_eq_of_mem hx hc hxH]; exact hyH
  · obtain ⟨k, hk2, hkeq⟩ := (Nat.dvd_prime_pow hp).mp hdvd
    have hk0 : k ≠ 0 := by
      rintro rfl; rw [pow_zero] at hkeq; rw [hkeq] at hpdvd
      exact (hp.one_lt.ne') (Nat.dvd_one.mp hpdvd)
    have hkne1 : k ≠ 1 := fun h => hc (by rw [hkeq, h, pow_one])
    have hk : k = 2 := by omega
    apply Subgroup.eq_top_of_card_eq
    rw [hkeq, hk, card_eq]

/-- A non-identity element of `C_p²` raised to a power coprime to `p` is again non-identity. -/
theorem pow_ne_one_of_not_dvd {x : CpSq p} (hx : x ≠ 1) {n : ℕ} (hn : ¬ p ∣ n) : x ^ n ≠ 1 := by
  intro h
  have hd : orderOf x ∣ n := orderOf_dvd_of_pow_eq_one h
  rw [orderOf_eq_p hx] at hd
  exact hn hd

/-- Raising a non-identity element of `C_p²` to a power coprime to `p` keeps the same line. -/
theorem zpowers_pow {x : CpSq p} (hx : x ≠ 1) {n : ℕ} (hn : ¬ p ∣ n) :
    Subgroup.zpowers (x ^ n) = Subgroup.zpowers x :=
  zpowers_eq_of_mem (pow_ne_one_of_not_dvd hx hn) (card_zpowers_eq_p hx)
    (pow_mem (Subgroup.mem_zpowers x) n)

/-- If the line `⟨x⟩` differs from an order-`p` subgroup `H`, then `x ∉ H`. -/
theorem not_mem_of_zpowers_ne {x : CpSq p} (hx : x ≠ 1) {H : Subgroup (CpSq p)}
    (hcard : Nat.card H = p) (hne : Subgroup.zpowers x ≠ H) : x ∉ H :=
  fun hmem => hne (zpowers_eq_of_mem hx hcard hmem)

/-- `⟨x⟩ ≠ ⟨y⟩` whenever `y` lies off the line `⟨x⟩`. -/
theorem zpowers_ne_of_not_mem {n : ℕ} {x y : CpSq n} (hxy : y ∉ Subgroup.zpowers x) :
    Subgroup.zpowers x ≠ Subgroup.zpowers y :=
  fun h => hxy (h.symm ▸ Subgroup.mem_zpowers y)

/-- A power of a generator off the line `⟨x⟩`: if `⟨v⟩ ≠ ⟨x⟩` and `p ∤ n` then `v ^ n ∉ ⟨x⟩`. -/
theorem pow_not_mem_of_zpowers_ne {x v : CpSq p} (hx : x ≠ 1) (hv : v ≠ 1) {n : ℕ}
    (hn : ¬ p ∣ n) (hne : Subgroup.zpowers v ≠ Subgroup.zpowers x) : v ^ n ∉ Subgroup.zpowers x :=
  not_mem_of_zpowers_ne (pow_ne_one_of_not_dvd hv hn) (card_zpowers_eq_p hx)
    (by rwa [zpowers_pow hv hn])

/-- If `c ∈ ⟨u⟩` but `d ∉ ⟨u⟩`, then `c * d ∉ ⟨u⟩`. -/
theorem mul_not_mem_left {n : ℕ} {u c d : CpSq n} (hc : c ∈ Subgroup.zpowers u)
    (hd : d ∉ Subgroup.zpowers u) : c * d ∉ Subgroup.zpowers u :=
  fun h => hd ((Subgroup.mul_mem_cancel_left _ hc).mp h)

/-- If `c ∉ ⟨u⟩` but `d ∈ ⟨u⟩`, then `c * d ∉ ⟨u⟩`. -/
theorem mul_not_mem_right {n : ℕ} {u c d : CpSq n} (hc : c ∉ Subgroup.zpowers u)
    (hd : d ∈ Subgroup.zpowers u) : c * d ∉ Subgroup.zpowers u :=
  fun h => hc ((Subgroup.mul_mem_cancel_right _ hd).mp h)

/-- For a prime `p ≠ k` (with `k` prime), `p` does not divide `k`. -/
theorem not_dvd_of_ne {k : ℕ} (hk : k.Prime) (h : p ≠ k) : ¬ p ∣ k := by
  intro hd
  rcases hk.eq_one_or_self_of_dvd p hd with h1 | h2
  · exact (Fact.out : p.Prime).ne_one h1
  · exact h h2

/-- **Generation from distinct lines.** Two non-identity elements of `C_p²` generating different
cyclic subgroups generate the whole group. -/
theorem closure_eq_top_of_zpowers_ne {x y : CpSq p} (hx : x ≠ 1) (hy : y ≠ 1)
    (hne : Subgroup.zpowers x ≠ Subgroup.zpowers y) :
    Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤ :=
  closure_eq_top hx (not_mem_of_zpowers_ne hy (card_zpowers_eq_p hx) (Ne.symm hne))

/-- **Distinct lines, first coordinate.** For a generating pair `(a, b)` and `p ∤ n`, the element
`a * bⁿ` lies off the line `⟨a⟩`, so `⟨a⟩ ≠ ⟨a*bⁿ⟩`. -/
theorem zpowers_fst_ne_mul_pow {a b : CpSq p}
    (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) {n : ℕ} (hn : ¬ p ∣ n) :
    Subgroup.zpowers a ≠ Subgroup.zpowers (a * b ^ n) :=
  zpowers_ne_of_not_mem (mul_not_mem_left (Subgroup.mem_zpowers a)
    (pow_not_mem_of_zpowers_ne (fst_ne_one hgen) (snd_ne_one hgen) hn
      (zpowers_fst_ne_snd hgen).symm))

/-- **Distinct lines, second coordinate.** For a generating pair `(a, b)`, the element `a * bⁿ`
lies off the line `⟨b⟩` (no condition on `n`), so `⟨b⟩ ≠ ⟨a*bⁿ⟩`. -/
theorem zpowers_snd_ne_mul_pow {a b : CpSq p}
    (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (n : ℕ) :
    Subgroup.zpowers b ≠ Subgroup.zpowers (a * b ^ n) :=
  zpowers_ne_of_not_mem (mul_not_mem_right
    (not_mem_of_zpowers_ne (fst_ne_one hgen) (card_zpowers_eq_p (snd_ne_one hgen))
      (zpowers_fst_ne_snd hgen))
    (pow_mem (Subgroup.mem_zpowers b) n))

/-- A non-identity multiple `x * yⁱ` (any `i`) of a generating pair is never the identity. -/
theorem mul_pow_ne_one {x y : CpSq p} (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤)
    (n : ℕ) : x * y ^ n ≠ 1 := by
  intro h
  refine not_mem_of_zpowers_ne (fst_ne_one hgen) (card_zpowers_eq_p (snd_ne_one hgen))
    (zpowers_fst_ne_snd hgen) ?_
  rw [eq_inv_of_mul_eq_one_left h]
  exact inv_mem (pow_mem (Subgroup.mem_zpowers y) n)

/-- Distinct small powers of a non-identity element of `C_p²` are distinct, provided their
exponents differ by less than `p`. -/
theorem pow_ne_pow_of_lt {x : CpSq p} (hx : x ≠ 1) {i j : ℕ} (hij : i < j) (hd : j - i < p) :
    x ^ i ≠ x ^ j := by
  intro h
  have hsplit : x ^ j = x ^ i * x ^ (j - i) := by
    rw [← pow_add]; congr 1; omega
  rw [hsplit] at h
  have h1 : x ^ (j - i) = 1 := mul_eq_left.mp h.symm
  have hdvd := orderOf_dvd_of_pow_eq_one h1
  rw [orderOf_eq_p hx] at hdvd
  have hpos : 0 < j - i := by omega
  exact absurd (Nat.le_of_dvd hpos hdvd) (by omega)

/-- For `p ≠ 2`, `p` does not divide `4`. -/
theorem not_dvd_four (hp2 : p ≠ 2) : ¬ p ∣ 4 := by
  intro hd
  have hp : p.Prime := Fact.out
  have h4 : (4 : ℕ) = 2 * 2 := by norm_num
  rw [h4] at hd
  rcases hp.dvd_mul.mp hd with h | h <;>
    exact hp2 ((Nat.prime_dvd_prime_iff_eq hp Nat.prime_two).mp h)

/-- **Distinct lines through powers of `y`.** If `yⁱ ≠ yʲ`, then `x * yⁱ` and `x * yʲ` generate
different cyclic subgroups. -/
theorem zpowers_mul_pow_ne_mul_pow {x y : CpSq p}
    (hgen : Subgroup.closure ({x, y} : Set (CpSq p)) = ⊤) {i j : ℕ} (hij : y ^ i ≠ y ^ j) :
    Subgroup.zpowers (x * y ^ i) ≠ Subgroup.zpowers (x * y ^ j) := by
  intro heq
  set H := Subgroup.zpowers (x * y ^ i) with hHdef
  have hcardH : Nat.card H = p := card_zpowers_eq_p (mul_pow_ne_one hgen i)
  have h1 : x * y ^ i ∈ H := Subgroup.mem_zpowers _
  have h2 : x * y ^ j ∈ H := heq ▸ Subgroup.mem_zpowers _
  set c := (x * y ^ i)⁻¹ * (x * y ^ j) with hcdef
  have hcH : c ∈ H := mul_mem (inv_mem h1) h2
  have hceq : c = (y ^ i)⁻¹ * y ^ j := by
    rw [hcdef]
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_inv]; abel
  have hcy : c ∈ Subgroup.zpowers y := by
    rw [hceq]
    exact mul_mem (inv_mem (pow_mem (Subgroup.mem_zpowers y) i))
      (pow_mem (Subgroup.mem_zpowers y) j)
  have hc1 : c ≠ 1 := by
    rw [hceq]
    intro hc0
    exact hij (inv_mul_eq_one.mp hc0)
  have hHzy : H = Subgroup.zpowers y := by
    rw [← zpowers_eq_of_mem hc1 hcardH hcH,
      zpowers_eq_of_mem hc1 (card_zpowers_eq_p (snd_ne_one hgen)) hcy]
  have h1' : x * y ^ i ∈ Subgroup.zpowers y := hHzy ▸ h1
  have hxy : x ∈ Subgroup.zpowers y := by
    have e : x = (x * y ^ i) * (y ^ i)⁻¹ := by
      apply Multiplicative.toAdd.injective; simp only [toAdd_mul, toAdd_inv]; abel
    rw [e]
    exact mul_mem h1' (inv_mem (pow_mem (Subgroup.mem_zpowers y) i))
  exact not_mem_of_zpowers_ne (fst_ne_one hgen) (card_zpowers_eq_p (snd_ne_one hgen))
    (zpowers_fst_ne_snd hgen) hxy

/-! ### The dimension-four construction

Throughout, `(a, b)` is a generating pair of `C_p²` and `p ≠ 2`. The four constituent lines are
`⟨a⟩, ⟨b⟩, ⟨a*b⟩, ⟨a*b²⟩`. -/

section Dim4

variable {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)

include hgen



include hp2

omit hp2 in
theorem zpowers_mul_ne_mul_sq : Subgroup.zpowers (a * b) ≠ Subgroup.zpowers (a * b ^ 2) := by
  refine zpowers_ne_of_not_mem ?_
  have e : a * b ^ 2 = (a * b) * b := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_pow]; abel
  rw [e]
  exact mul_not_mem_left (Subgroup.mem_zpowers (a * b))
    (not_mem_of_zpowers_ne (snd_ne_one hgen) (card_zpowers_eq_p (mul_ne_one hgen))
      (zpowers_snd_ne_mul hgen))

theorem sigma_d1 : sigmaSet a (b ^ 2) =
    ↑(Subgroup.zpowers a) ∪ ↑(Subgroup.zpowers b) ∪ ↑(Subgroup.zpowers (a * b ^ 2)) := by
  rw [sigmaSet_of_comm, zpowers_pow (snd_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2)]

theorem sigma_d2 : sigmaSet a⁻¹ ((a * b) ^ 2) =
    ↑(Subgroup.zpowers a) ∪ ↑(Subgroup.zpowers (a * b)) ∪ ↑(Subgroup.zpowers (a * b ^ 2)) := by
  rw [sigmaSet_of_comm, Subgroup.zpowers_inv,
    zpowers_pow (mul_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2)]
  have : a⁻¹ * (a * b) ^ 2 = a * b ^2 := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_inv, toAdd_pow]; abel
  rw [this]

end Dim4

theorem sigma_d3 {n : ℕ} {a b : CpSq n} : sigmaSet b (a * b) =
    ↑(Subgroup.zpowers b) ∪ ↑(Subgroup.zpowers (a * b)) ∪ ↑(Subgroup.zpowers (a * b ^ 2)) := by
  rw [sigmaSet_of_comm]
  have : b * (a * b) = a * b ^ 2 := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_pow]; abel
  rw [this]

/-- The four generating pairs of the dimension-4 Beauville structure of `C_p²`. -/
def pairs4 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2) :
    Fin 4 → GeneratingPair (CpSq p)
  | 0 => ⟨a, b, hgen⟩
  | 1 => ⟨a, b ^ 2, closure_eq_top_of_zpowers_ne (fst_ne_one hgen)
      (pow_ne_one_of_not_dvd (snd_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2))
      (by rw [zpowers_pow (snd_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2)]
          exact zpowers_fst_ne_snd hgen)⟩
  | 2 => ⟨a⁻¹, (a * b) ^ 2, closure_eq_top_of_zpowers_ne (inv_ne_one.mpr (fst_ne_one hgen))
      (pow_ne_one_of_not_dvd (mul_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2))
      (by rw [Subgroup.zpowers_inv,
            zpowers_pow (mul_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2)]
          exact zpowers_fst_ne_mul hgen)⟩
  | 3 => ⟨b, a * b, closure_eq_top_of_zpowers_ne (snd_ne_one hgen) (mul_ne_one hgen)
      (zpowers_snd_ne_mul hgen)⟩

/-- The four Σ-sets of the dimension-4 family meet only in the identity. -/
theorem inter4_eq_one {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) :
    (⋂ i, sigmaSet (pairs4 hgen hp2 i).x (pairs4 hgen hp2 i).y) = {1} := by
  apply Set.eq_singleton_iff_unique_mem.mpr
  refine ⟨Set.mem_iInter.mpr (fun i => one_mem_sigmaSet _ _), ?_⟩
  intro g hg
  rw [Set.mem_iInter] at hg
  by_contra hg1
  have h0 : g ∈ sigmaSet a b := hg 0
  have h1 : g ∈ sigmaSet a (b ^ 2) := hg 1
  have h2 : g ∈ sigmaSet a⁻¹ ((a * b) ^ 2) := hg 2
  have h3 : g ∈ sigmaSet b (a * b) := hg 3
  rw [sigmaSet_of_comm] at h0
  rw [sigma_d1 hgen hp2] at h1
  rw [sigma_d2 hgen hp2] at h2
  rw [sigma_d3] at h3
  have ca := card_zpowers_eq_p (fst_ne_one hgen)
  have cb := card_zpowers_eq_p (snd_ne_one hgen)
  have cab := card_zpowers_eq_p (mul_ne_one hgen)
  have cab2 := card_zpowers_eq_p (mul_pow_ne_one hgen 2)
  have d12 := zpowers_fst_ne_snd hgen
  have d13 := zpowers_fst_ne_mul hgen
  have d23 := zpowers_snd_ne_mul hgen
  have d14 := zpowers_fst_ne_mul_pow hgen (not_dvd_of_ne Nat.prime_two hp2)
  have d24 := zpowers_snd_ne_mul_pow hgen 2
  have d34 := zpowers_mul_ne_mul_sq hgen
  simp only [Set.mem_union, SetLike.mem_coe] at h0 h1 h2 h3
  rcases h0 with (hL1 | hL2) | hL3
  · rcases h3 with (hL2 | hL3) | hL4
    · exact d12 (eq_of_mem_of_mem hg1 ca cb hL1 hL2)
    · exact d13 (eq_of_mem_of_mem hg1 ca cab hL1 hL3)
    · exact d14 (eq_of_mem_of_mem hg1 ca cab2 hL1 hL4)
  · rcases h2 with (hL1 | hL3) | hL4
    · exact d12 (eq_of_mem_of_mem hg1 ca cb hL1 hL2)
    · exact d23 (eq_of_mem_of_mem hg1 cb cab hL2 hL3)
    · exact d24 (eq_of_mem_of_mem hg1 cb cab2 hL2 hL4)
  · rcases h1 with (hL1 | hL2) | hL4
    · exact d13 (eq_of_mem_of_mem hg1 ca cab hL1 hL3)
    · exact d23 (eq_of_mem_of_mem hg1 cb cab hL2 hL3)
    · exact d34 (eq_of_mem_of_mem hg1 cab cab2 hL3 hL4)

/-- The dimension-4 generalised Beauville structure of `C_p²` from a generating pair `(a, b)`. -/
def beauville4 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2) :
    GeneralisedBeauvilleStructure (CpSq p) where
  ι := Fin 4
  pairs := pairs4 hgen hp2
  inter_sigmaSet_eq_one := inter4_eq_one hgen hp2

theorem primitive4 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) : (beauville4 hgen hp2).IsPrimitive := by
  intro S hS
  have hex : ∃ j : Fin 4, j ∉ S := by
    by_contra hcon
    simp only [not_exists, not_not] at hcon
    exact hS (Finset.eq_univ_iff_forall.mpr hcon)
  obtain ⟨j, hj⟩ := hex
  obtain ⟨w, hw1, hwi⟩ : ∃ w : CpSq p, w ≠ 1 ∧
      ∀ i : Fin 4, i ≠ j → w ∈ sigmaSet (pairs4 hgen hp2 i).x (pairs4 hgen hp2 i).y := by
    fin_cases j
    · refine ⟨a * b ^ 2, mul_pow_ne_one hgen 2, fun i hi => ?_⟩
      fin_cases i
      · exact absurd rfl hi
      · change a * b ^ 2 ∈ sigmaSet a (b ^ 2)
        rw [sigma_d1 hgen hp2]; exact Or.inr (Subgroup.mem_zpowers _)
      · change a * b ^ 2 ∈ sigmaSet a⁻¹ ((a * b) ^ 2)
        rw [sigma_d2 hgen hp2]; exact Or.inr (Subgroup.mem_zpowers _)
      · change a * b ^ 2 ∈ sigmaSet b (a * b)
        rw [sigma_d3]; exact Or.inr (Subgroup.mem_zpowers _)
    · refine ⟨a * b, mul_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change a * b ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inr (Subgroup.mem_zpowers _)
      · exact absurd rfl hi
      · change a * b ∈ sigmaSet a⁻¹ ((a * b) ^ 2)
        rw [sigma_d2 hgen hp2]; exact Or.inl (Or.inr (Subgroup.mem_zpowers _))
      · change a * b ∈ sigmaSet b (a * b)
        rw [sigma_d3]; exact Or.inl (Or.inr (Subgroup.mem_zpowers _))
    · refine ⟨b, snd_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change b ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inl (Or.inr (Subgroup.mem_zpowers _))
      · change b ∈ sigmaSet a (b ^ 2)
        rw [sigma_d1 hgen hp2]; exact Or.inl (Or.inr (Subgroup.mem_zpowers _))
      · exact absurd rfl hi
      · change b ∈ sigmaSet b (a * b)
        rw [sigma_d3]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
    · refine ⟨a, fst_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change a ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · change a ∈ sigmaSet a (b ^ 2)
        rw [sigma_d1 hgen hp2]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · change a ∈ sigmaSet a⁻¹ ((a * b) ^ 2)
        rw [sigma_d2 hgen hp2]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · exact absurd rfl hi
  intro hcontra
  have hwmem : w ∈ ⋂ i ∈ S, sigmaSet ((beauville4 hgen hp2).pairs i).x
      ((beauville4 hgen hp2).pairs i).y :=
    Set.mem_iInter₂.mpr (fun i hi => hwi i (fun e => hj (e ▸ hi)))
  rw [hcontra, Set.mem_singleton_iff] at hwmem
  exact hw1 hwmem

/-- The standard basis `(1,0), (0,1)` is a generating pair of `C_p²`. -/
theorem basis_gen : Subgroup.closure
    ({Multiplicative.ofAdd (1, 0), Multiplicative.ofAdd (0, 1)} : Set (CpSq p)) = ⊤ := by
  apply closure_eq_top
  · intro h
    have h2 : ((1 : ZMod p), (0 : ZMod p)) = 0 := by
      have h3 := congrArg Multiplicative.toAdd h
      simp only [toAdd_ofAdd, toAdd_one] at h3
      exact h3
    rw [Prod.ext_iff] at h2
    exact one_ne_zero h2.1
  · apply not_mem_zpowers_of_hom (AddMonoidHom.snd (ZMod p) (ZMod p))
    · simp
    · simp

/-- **`4 ∈ BSpec(C_p²)`** for odd primes `p`. -/
theorem four_mem_BSpec (hp2 : p ≠ 2) : 4 ∈ BeauvilleSpectrum (CpSq p) :=
  ⟨beauville4 basis_gen hp2, primitive4 basis_gen hp2, by
    rw [GeneralisedBeauvilleStructure.dimension]; exact Fintype.card_fin 4⟩

/-- **Proposition.** For odd primes `p`, the maximum of `BSpec(C_p²)` is `4`. -/
theorem isGreatest_BSpec (hp2 : p ≠ 2) : IsGreatest (BeauvilleSpectrum (CpSq p)) 4 :=
  ⟨four_mem_BSpec hp2, by
    rintro d ⟨B, hBprim, rfl⟩
    exact dimension_le_four B hBprim⟩

/-! ### The minimum of `BSpec(C_p²)` -/

/-- **Lower floor.** Every `GeneralisedBeauvilleStructure (CpSq p)` has dimension at least `2`:
dimension `0` would force `⋂ᵢ Σᵢ = univ`, impossible since `C_p²` is nontrivial; dimension `1`
would force a single Σ-set to equal `{1}`, impossible since it contains its non-identity
generator. -/
theorem two_le_dimension (B : GeneralisedBeauvilleStructure (CpSq p)) : 2 ≤ B.dimension := by
  rw [GeneralisedBeauvilleStructure.dimension]
  by_contra hlt
  have hcase : Fintype.card B.ι = 0 ∨ Fintype.card B.ι = 1 := by omega
  rcases hcase with hc | hc
  · have hempty : IsEmpty B.ι := Fintype.card_eq_zero_iff.mp hc
    have huniv : (⋂ i, sigmaSet (B.pairs i).x (B.pairs i).y) = Set.univ := Set.iInter_of_empty _
    rw [B.inter_sigmaSet_eq_one] at huniv
    have hmem : Multiplicative.ofAdd ((1 : ZMod p), (0 : ZMod p)) ∈ ({1} : Set (CpSq p)) := by
      rw [huniv]; exact Set.mem_univ _
    exact fst_ne_one basis_gen (Set.mem_singleton_iff.mp hmem)
  · obtain ⟨i₀, hi₀⟩ := Fintype.card_eq_one_iff.mp hc
    have hx_mem : (B.pairs i₀).x ∈ ⋂ i, sigmaSet (B.pairs i).x (B.pairs i).y := by
      rw [Set.mem_iInter]
      intro i
      rw [hi₀ i]
      exact Group.subset_conjugatesOfSet (Or.inl (Or.inl (Subgroup.mem_zpowers _)))
    rw [B.inter_sigmaSet_eq_one, Set.mem_singleton_iff] at hx_mem
    exact fst_ne_one (B.pairs i₀).generates hx_mem

/-- **Line-set.** An explicit `Finset` enumerating the `p + 1` order-`p` subgroups ("lines") of
`C_p²`: the order-`p` subgroups partition the `p² - 1` non-identity elements into blocks of size
`p - 1` (the non-identity elements of each line). -/
theorem exists_lines_finset : ∃ L : Finset (Subgroup (CpSq p)), L.card = p + 1 ∧
    ∀ H : Subgroup (CpSq p), H ∈ L ↔ Nat.card H = p := by
  classical
  set S : Finset (CpSq p) := Finset.univ.erase 1 with hS
  have hScard : S.card = p ^ 2 - 1 := by
    rw [hS, Finset.card_erase_of_mem (Finset.mem_univ 1), Finset.card_univ,
      ← Nat.card_eq_fintype_card, card_eq]
  set f : CpSq p → Subgroup (CpSq p) := fun g => Subgroup.zpowers g with hf
  have hfiber : ∀ H ∈ S.image f, (S.filter (fun g => f g = H)).card = p - 1 := by
    intro H hH
    obtain ⟨g₀, hg₀S, hg₀eq⟩ := Finset.mem_image.mp hH
    have hg₀1 : g₀ ≠ 1 := (Finset.mem_erase.mp hg₀S).1
    have hHcard : Nat.card H = p := by rw [← hg₀eq]; exact card_zpowers_eq_p hg₀1
    have hset : S.filter (fun g => f g = H) = (Finset.univ.filter (· ∈ H)).erase 1 := by
      ext g
      simp only [Finset.mem_filter, Finset.mem_univ, true_and, and_true, hS, Finset.mem_erase, hf]
      constructor
      · rintro ⟨hg1, hzg⟩
        exact ⟨hg1, by rw [← hzg]; exact Subgroup.mem_zpowers g⟩
      · rintro ⟨hg1, hgH⟩
        exact ⟨hg1, zpowers_eq_of_mem hg1 hHcard hgH⟩
    rw [hset, Finset.card_erase_of_mem (Finset.mem_filter.mpr ⟨Finset.mem_univ 1, one_mem H⟩)]
    have hcardSub : (Finset.univ.filter (· ∈ H)).card = Nat.card H := by
      rw [← Fintype.card_subtype (· ∈ H), ← Nat.card_eq_fintype_card]
    rw [hcardSub, hHcard]
  have hsum : S.card = ∑ H ∈ S.image f, (S.filter (fun g => f g = H)).card :=
    Finset.card_eq_sum_card_image f S
  rw [Finset.sum_congr rfl hfiber, Finset.sum_const, smul_eq_mul, hScard] at hsum
  have hp : p.Prime := Fact.out
  have e0 : p ^ 2 = (p + 1) * (p - 1) + 1 := by
    rcases Nat.exists_eq_add_of_le hp.two_le with ⟨k, hk⟩
    subst hk
    have hsub : 2 + k - 1 = k + 1 := by omega
    rw [hsub]; ring
  have e1 : p ^ 2 - 1 = (p + 1) * (p - 1) := by omega
  have key : (S.image f).card * (p - 1) = (p + 1) * (p - 1) := hsum.symm.trans e1
  have hp1pos : 0 < p - 1 := by have := hp.two_le; omega
  have hcard : (S.image f).card = p + 1 := Nat.eq_of_mul_eq_mul_right hp1pos key
  have hcoe : (↑(S.image f) : Set (Subgroup (CpSq p)))
      = {H : Subgroup (CpSq p) | Nat.card H = p} := by
    ext H
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Set.mem_setOf_eq]
    constructor
    · rintro ⟨g, hgS, rfl⟩
      exact card_zpowers_eq_p (Finset.mem_erase.mp hgS).1
    · intro hHcard
      have hne_bot : H ≠ ⊥ := by
        rw [← Subgroup.one_lt_card_iff_ne_bot, hHcard]; exact hp.one_lt
      obtain ⟨g, hgH, hg1⟩ := (Subgroup.nontrivial_iff_exists_ne_one H).mp
        ((Subgroup.nontrivial_iff_ne_bot H).mpr hne_bot)
      exact ⟨g, Finset.mem_erase.mpr ⟨hg1, Finset.mem_univ g⟩, zpowers_eq_of_mem hg1 hHcard hgH⟩
  exact ⟨S.image f, hcard, fun H => by rw [← Finset.mem_coe, hcoe, Set.mem_setOf_eq]⟩

/-- **Line count.** `C_p²` has exactly `p + 1` order-`p` subgroups ("lines"). -/
theorem ncard_lines_eq : {H : Subgroup (CpSq p) | Nat.card H = p}.ncard = p + 1 := by
  obtain ⟨L, hLcard, hLmem⟩ := exists_lines_finset (p := p)
  have hset : {H : Subgroup (CpSq p) | Nat.card H = p} = (↑L : Set (Subgroup (CpSq p))) := by
    ext H; simp [hLmem H]
  rw [hset, Set.ncard_coe_finset, hLcard]

/-! ### The dimension-two construction (for `p ≥ 5`)

The two pairs are `(a, b)` and `((a*b²)⁻¹, (a*b³)²)`; the six constituent lines
`⟨a⟩, ⟨b⟩, ⟨a*b⟩, ⟨a*b²⟩, ⟨a*b³⟩, ⟨a*b⁴⟩` are pairwise distinct for `p ≥ 5`. -/

section Dim2

variable {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)

include hgen hp2

theorem sigma_f2 : sigmaSet (a * b ^ 2)⁻¹ ((a * b ^ 3) ^ 2) =
    ↑(Subgroup.zpowers (a * b ^ 2)) ∪ ↑(Subgroup.zpowers (a * b ^ 3)) ∪
      ↑(Subgroup.zpowers (a * b ^ 4)) := by
  have e : (a * b ^ 2)⁻¹ * (a * b ^ 3) ^ 2 = a * b ^ 4 := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_inv, toAdd_pow]; abel
  rw [sigmaSet_of_comm, Subgroup.zpowers_inv,
    zpowers_pow (mul_pow_ne_one hgen 3) (not_dvd_of_ne Nat.prime_two hp2), e]

end Dim2

/-- The two generating pairs of the dimension-2 Beauville structure of `C_p²` (`p ≥ 5`). -/
def pairs2 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)
    (_hp3 : p ≠ 3) : Fin 2 → GeneratingPair (CpSq p)
  | 0 => ⟨a, b, hgen⟩
  | 1 => ⟨(a * b ^ 2)⁻¹, (a * b ^ 3) ^ 2,
      closure_eq_top_of_zpowers_ne (inv_ne_one.mpr (mul_pow_ne_one hgen 2))
        (pow_ne_one_of_not_dvd (mul_pow_ne_one hgen 3) (not_dvd_of_ne Nat.prime_two hp2))
        (by rw [Subgroup.zpowers_inv,
              zpowers_pow (mul_pow_ne_one hgen 3) (not_dvd_of_ne Nat.prime_two hp2)]
            exact zpowers_mul_pow_ne_mul_pow hgen
              (pow_ne_pow_of_lt (snd_ne_one hgen) (by norm_num)
                (by have := (Fact.out : p.Prime).two_le; omega)))⟩

/-- The two Σ-sets of the dimension-2 family meet only in the identity. -/
theorem inter2_eq_one {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) (hp3 : p ≠ 3) :
    (⋂ i, sigmaSet (pairs2 hgen hp2 hp3 i).x (pairs2 hgen hp2 hp3 i).y) = {1} := by
  apply Set.eq_singleton_iff_unique_mem.mpr
  refine ⟨Set.mem_iInter.mpr (fun i => one_mem_sigmaSet _ _), ?_⟩
  intro g hg
  rw [Set.mem_iInter] at hg
  by_contra hg1
  have h0 : g ∈ sigmaSet a b := hg 0
  have h1 : g ∈ sigmaSet (a * b ^ 2)⁻¹ ((a * b ^ 3) ^ 2) := hg 1
  rw [sigmaSet_of_comm] at h0
  rw [sigma_f2 hgen hp2] at h1
  have hp : p.Prime := Fact.out
  have hp2le := hp.two_le
  have ca := card_zpowers_eq_p (fst_ne_one hgen)
  have cb := card_zpowers_eq_p (snd_ne_one hgen)
  have cab := card_zpowers_eq_p (mul_ne_one hgen)
  have cab2 := card_zpowers_eq_p (mul_pow_ne_one hgen 2)
  have cab3 := card_zpowers_eq_p (mul_pow_ne_one hgen 3)
  have cab4 := card_zpowers_eq_p (mul_pow_ne_one hgen 4)
  have hb12 : b ^ 1 ≠ b ^ 2 := pow_ne_pow_of_lt (snd_ne_one hgen) (by norm_num) (by omega)
  have hb13 : b ^ 1 ≠ b ^ 3 := pow_ne_pow_of_lt (snd_ne_one hgen) (by norm_num) (by omega)
  have hb14 : b ^ 1 ≠ b ^ 4 := pow_ne_pow_of_lt (snd_ne_one hgen) (by norm_num) (by omega)
  have d_a_ab2 : Subgroup.zpowers a ≠ Subgroup.zpowers (a * b ^ 2) :=
    zpowers_fst_ne_mul_pow hgen (not_dvd_of_ne Nat.prime_two hp2)
  have d_a_ab3 : Subgroup.zpowers a ≠ Subgroup.zpowers (a * b ^ 3) :=
    zpowers_fst_ne_mul_pow hgen (not_dvd_of_ne Nat.prime_three hp3)
  have d_a_ab4 : Subgroup.zpowers a ≠ Subgroup.zpowers (a * b ^ 4) :=
    zpowers_fst_ne_mul_pow hgen (not_dvd_four hp2)
  have d_b_ab2 : Subgroup.zpowers b ≠ Subgroup.zpowers (a * b ^ 2) := zpowers_snd_ne_mul_pow hgen 2
  have d_b_ab3 : Subgroup.zpowers b ≠ Subgroup.zpowers (a * b ^ 3) := zpowers_snd_ne_mul_pow hgen 3
  have d_b_ab4 : Subgroup.zpowers b ≠ Subgroup.zpowers (a * b ^ 4) := zpowers_snd_ne_mul_pow hgen 4
  have d_ab_ab2 : Subgroup.zpowers (a * b) ≠ Subgroup.zpowers (a * b ^ 2) := by
    have h := zpowers_mul_pow_ne_mul_pow hgen hb12; rwa [pow_one] at h
  have d_ab_ab3 : Subgroup.zpowers (a * b) ≠ Subgroup.zpowers (a * b ^ 3) := by
    have h := zpowers_mul_pow_ne_mul_pow hgen hb13; rwa [pow_one] at h
  have d_ab_ab4 : Subgroup.zpowers (a * b) ≠ Subgroup.zpowers (a * b ^ 4) := by
    have h := zpowers_mul_pow_ne_mul_pow hgen hb14; rwa [pow_one] at h
  simp only [Set.mem_union, SetLike.mem_coe] at h0 h1
  rcases h0 with (hL1 | hL2) | hL3
  · rcases h1 with (hM2 | hM3) | hM4
    · exact d_a_ab2 (eq_of_mem_of_mem hg1 ca cab2 hL1 hM2)
    · exact d_a_ab3 (eq_of_mem_of_mem hg1 ca cab3 hL1 hM3)
    · exact d_a_ab4 (eq_of_mem_of_mem hg1 ca cab4 hL1 hM4)
  · rcases h1 with (hM2 | hM3) | hM4
    · exact d_b_ab2 (eq_of_mem_of_mem hg1 cb cab2 hL2 hM2)
    · exact d_b_ab3 (eq_of_mem_of_mem hg1 cb cab3 hL2 hM3)
    · exact d_b_ab4 (eq_of_mem_of_mem hg1 cb cab4 hL2 hM4)
  · rcases h1 with (hM2 | hM3) | hM4
    · exact d_ab_ab2 (eq_of_mem_of_mem hg1 cab cab2 hL3 hM2)
    · exact d_ab_ab3 (eq_of_mem_of_mem hg1 cab cab3 hL3 hM3)
    · exact d_ab_ab4 (eq_of_mem_of_mem hg1 cab cab4 hL3 hM4)

/-- The dimension-2 generalised Beauville structure of `C_p²` (for `p ≥ 5`). -/
def beauville2 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)
    (hp3 : p ≠ 3) : GeneralisedBeauvilleStructure (CpSq p) where
  ι := Fin 2
  pairs := pairs2 hgen hp2 hp3
  inter_sigmaSet_eq_one := inter2_eq_one hgen hp2 hp3

theorem primitive2 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) (hp3 : p ≠ 3) : (beauville2 hgen hp2 hp3).IsPrimitive := by
  intro S hS
  have hex : ∃ j : Fin 2, j ∉ S := by
    by_contra hcon
    simp only [not_exists, not_not] at hcon
    exact hS (Finset.eq_univ_iff_forall.mpr hcon)
  obtain ⟨j, hj⟩ := hex
  obtain ⟨w, hw1, hwi⟩ : ∃ w : CpSq p, w ≠ 1 ∧
      ∀ i : Fin 2, i ≠ j → w ∈ sigmaSet (pairs2 hgen hp2 hp3 i).x (pairs2 hgen hp2 hp3 i).y := by
    fin_cases j
    · refine ⟨a * b ^ 2, mul_pow_ne_one hgen 2, fun i hi => ?_⟩
      fin_cases i
      · exact absurd rfl hi
      · change a * b ^ 2 ∈ sigmaSet (a * b ^ 2)⁻¹ ((a * b ^ 3) ^ 2)
        rw [sigma_f2 hgen hp2]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
    · refine ⟨a, fst_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change a ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · exact absurd rfl hi
  intro hcontra
  have hwmem : w ∈ ⋂ i ∈ S, sigmaSet ((beauville2 hgen hp2 hp3).pairs i).x
      ((beauville2 hgen hp2 hp3).pairs i).y :=
    Set.mem_iInter₂.mpr (fun i hi => hwi i (fun e => hj (e ▸ hi)))
  rw [hcontra, Set.mem_singleton_iff] at hwmem
  exact hw1 hwmem

/-- **`2 ∈ BSpec(C_p²)`** for primes `p ≥ 5`. -/
theorem two_mem_BSpec (hp2 : p ≠ 2) (hp3 : p ≠ 3) : 2 ∈ BeauvilleSpectrum (CpSq p) :=
  ⟨beauville2 basis_gen hp2 hp3, primitive2 basis_gen hp2 hp3, by
    rw [GeneralisedBeauvilleStructure.dimension]; exact Fintype.card_fin 2⟩

/-! ### `p = 3`: the minimum of `BSpec(C_3²)` is `4` -/

/-- For `p = 3`, every primitive structure has dimension `≥ 4`. Each Σ-set contains exactly `3`
of the `4` lines of `C_3²`, so misses exactly `1`; since `⋂ᵢ Σᵢ = {1}`, every line (having
`3 > 1` elements) must be missed by some `Σᵢ` (`exists_sigmaSet_not_subset`). The `4` lines are
thus covered by the (size-`1`) "missed-line" sets of the `Fintype.card B.ι` indices, forcing
`4 ≤ Fintype.card B.ι`. -/
theorem four_le_dimension_of_three (hp3 : p = 3) (B : GeneralisedBeauvilleStructure (CpSq p))
    (hB : B.IsPrimitive) : 4 ≤ B.dimension := by
  classical
  subst hp3
  obtain ⟨L, hLcard, hLmem⟩ := exists_lines_finset (p := 3)
  set Li : B.ι → Finset (Subgroup (CpSq 3)) :=
    fun i => L.filter (fun H => (↑H : Set (CpSq 3)) ⊆ sigmaSet (B.pairs i).x (B.pairs i).y)
    with hLi
  have hLi_sub : ∀ i, Li i ⊆ L := fun i => by simp only [hLi]; exact Finset.filter_subset _ _
  have hLi_card : ∀ i, (Li i).card = 3 := by
    intro i
    have hset : (↑(Li i) : Set (Subgroup (CpSq 3)))
        = {H : Subgroup (CpSq 3) | Nat.card H = 3 ∧
            (↑H : Set (CpSq 3)) ⊆ sigmaSet (B.pairs i).x (B.pairs i).y} := by
      ext H
      simp only [hLi, Finset.coe_filter, Set.mem_setOf_eq, hLmem H]
    rw [← Set.ncard_coe_finset, hset]
    exact ncard_lines_of_sigmaSet (B.pairs i).generates
  set Mi : B.ι → Finset (Subgroup (CpSq 3)) := fun i => L \ Li i with hMi
  have hMi_card : ∀ i, (Mi i).card = 1 := by
    intro i
    simp only [hMi, Finset.card_sdiff_of_subset (hLi_sub i), hLi_card i, hLcard]
  have hcover : L ⊆ Finset.univ.biUnion Mi := by
    intro H hHL
    have hHcard : Nat.card H = 3 := (hLmem H).mp hHL
    obtain ⟨g, hgH, hg1⟩ := (Subgroup.nontrivial_iff_exists_ne_one H).mp
      ((Subgroup.nontrivial_iff_ne_bot H).mpr (by
        rw [← Subgroup.one_lt_card_iff_ne_bot, hHcard]; norm_num))
    obtain ⟨i, hi⟩ := B.exists_sigmaSet_not_subset ⟨g, hgH, hg1⟩
    refine Finset.mem_biUnion.mpr ⟨i, Finset.mem_univ i, ?_⟩
    simp only [hMi, hLi, Finset.mem_sdiff, Finset.mem_filter]
    exact ⟨hHL, fun hLiH => hi hLiH.2⟩
  have h4 : L.card ≤ (Finset.univ.biUnion Mi).card := Finset.card_le_card hcover
  have hsum_le : (Finset.univ.biUnion Mi).card ≤ ∑ i : B.ι, (Mi i).card := Finset.card_biUnion_le
  have hsum_eq : ∑ i : B.ι, (Mi i).card = Fintype.card B.ι := by
    simp [hMi_card, Finset.card_univ]
  rw [GeneralisedBeauvilleStructure.dimension]
  omega

/-! ### External input: the minimum (Remark / Carta–Fairbairn, Thm 2.9) -/

/-- **Proposition (cf. Carta–Fairbairn, Generalised Beauville Groups, Thm 2.9).** For odd primes
`p`, the minimum of `BSpec(C_p²)` is `4` when `p = 3` and `2` otherwise. -/
theorem isLeast_BSpec (hp2 : p ≠ 2) :
    IsLeast (BeauvilleSpectrum (CpSq p)) (if p = 3 then 4 else 2) := by
  by_cases hp3 : p = 3
  · rw [if_pos hp3]
    subst hp3
    refine ⟨four_mem_BSpec hp2, ?_⟩
    rintro d ⟨B, hBprim, rfl⟩
    exact four_le_dimension_of_three rfl B hBprim
  · rw [if_neg hp3]
    refine ⟨two_mem_BSpec hp2 hp3, ?_⟩
    rintro d ⟨B, hBprim, rfl⟩
    exact two_le_dimension B

/-! ### The dimension-three construction (for `p ≥ 5`)

The three pairs are `(a, b)`, `(a, b²)`, `((a*b)⁻¹, (a*b²)²)`; the constituent lines are
`⟨a⟩, ⟨b⟩, ⟨a*b⟩, ⟨a*b²⟩, ⟨a*b³⟩`, the last requiring `p ≠ 3` to be distinct from `⟨a⟩`. -/

section Dim3

variable {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
  (hp2 : p ≠ 2) (hp3 : p ≠ 3)

include hgen


include hp2

theorem sigma_e2 : sigmaSet (a * b)⁻¹ ((a * b ^ 2) ^ 2) =
    ↑(Subgroup.zpowers (a * b)) ∪ ↑(Subgroup.zpowers (a * b ^ 2)) ∪
      ↑(Subgroup.zpowers (a * b ^ 3)) := by
  have e : (a * b)⁻¹ * (a * b ^ 2) ^ 2 = a * b ^ 3 := by
    apply Multiplicative.toAdd.injective
    simp only [toAdd_mul, toAdd_inv, toAdd_pow]; abel
  rw [sigmaSet_of_comm, Subgroup.zpowers_inv,
    zpowers_pow (mul_pow_ne_one hgen 2) (not_dvd_of_ne Nat.prime_two hp2), e]

end Dim3

omit [Fact p.Prime] in
/-- **Consistency Remark.** When `p = 3`, the line `⟨a*b³⟩` coincides with `⟨a⟩` (since
`b³ = b^p = 1`). This is exactly why the dimension-3 construction requires `p ≠ 3`: at `p = 3`
the Σ-set `Σ((a*b)⁻¹, (a*b²)²)` no longer meets `Σ(a, b)` only in the identity, consistent with
`min(BSpec(C₃²)) = 4`. -/
theorem zpowers_mul_cube_eq_of_three (hp3 : p = 3) {a b : CpSq p} :
    Subgroup.zpowers (a * b ^ 3) = Subgroup.zpowers a := by
  have hb : b ^ 3 = 1 := by rw [← hp3]; exact pow_eq_one b
  rw [hb, mul_one]

/-- The three generating pairs of the dimension-3 Beauville structure of `C_p²` (`p ≥ 5`). -/
def pairs3 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)
    (_hp3 : p ≠ 3) : Fin 3 → GeneratingPair (CpSq p)
  | 0 => ⟨a, b, hgen⟩
  | 1 => ⟨a, b ^ 2, closure_eq_top_of_zpowers_ne (fst_ne_one hgen)
      (pow_ne_one_of_not_dvd (snd_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2))
      (by rw [zpowers_pow (snd_ne_one hgen) (not_dvd_of_ne Nat.prime_two hp2)]
          exact zpowers_fst_ne_snd hgen)⟩
  | 2 => ⟨(a * b)⁻¹, (a * b ^ 2) ^ 2,
      closure_eq_top_of_zpowers_ne (inv_ne_one.mpr (mul_ne_one hgen))
        (pow_ne_one_of_not_dvd (mul_pow_ne_one hgen 2) (not_dvd_of_ne Nat.prime_two hp2))
        (by rw [Subgroup.zpowers_inv,
              zpowers_pow (mul_pow_ne_one hgen 2) (not_dvd_of_ne Nat.prime_two hp2)]
            exact zpowers_mul_ne_mul_sq hgen)⟩

theorem inter3_eq_one {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) (hp3 : p ≠ 3) :
    (⋂ i, sigmaSet (pairs3 hgen hp2 hp3 i).x (pairs3 hgen hp2 hp3 i).y) = {1} := by
  apply Set.eq_singleton_iff_unique_mem.mpr
  refine ⟨Set.mem_iInter.mpr (fun i => one_mem_sigmaSet _ _), ?_⟩
  intro g hg
  rw [Set.mem_iInter] at hg
  by_contra hg1
  have h0 : g ∈ sigmaSet a b := hg 0
  have h1 : g ∈ sigmaSet a (b ^ 2) := hg 1
  have h2 : g ∈ sigmaSet (a * b)⁻¹ ((a * b ^ 2) ^ 2) := hg 2
  rw [sigmaSet_of_comm] at h0
  rw [sigma_d1 hgen hp2] at h1
  rw [sigma_e2 hgen hp2] at h2
  have ca := card_zpowers_eq_p (fst_ne_one hgen)
  have cb := card_zpowers_eq_p (snd_ne_one hgen)
  have cab := card_zpowers_eq_p (mul_ne_one hgen)
  have cab2 := card_zpowers_eq_p (mul_pow_ne_one hgen 2)
  have cab3 := card_zpowers_eq_p (mul_pow_ne_one hgen 3)
  have d13 := zpowers_fst_ne_mul hgen
  have d23 := zpowers_snd_ne_mul hgen
  have d14 := zpowers_fst_ne_mul_pow hgen (not_dvd_of_ne Nat.prime_two hp2)
  have d24 := zpowers_snd_ne_mul_pow hgen 2
  have d34 := zpowers_mul_ne_mul_sq hgen
  have d15 := zpowers_fst_ne_mul_pow hgen (not_dvd_of_ne Nat.prime_three hp3)
  have d25 := zpowers_snd_ne_mul_pow hgen 3
  simp only [Set.mem_union, SetLike.mem_coe] at h0 h1 h2
  rcases h0 with (hL1 | hL2) | hL3
  · rcases h2 with (hL3 | hL4) | hL5
    · exact d13 (eq_of_mem_of_mem hg1 ca cab hL1 hL3)
    · exact d14 (eq_of_mem_of_mem hg1 ca cab2 hL1 hL4)
    · exact d15 (eq_of_mem_of_mem hg1 ca cab3 hL1 hL5)
  · rcases h2 with (hL3 | hL4) | hL5
    · exact d23 (eq_of_mem_of_mem hg1 cb cab hL2 hL3)
    · exact d24 (eq_of_mem_of_mem hg1 cb cab2 hL2 hL4)
    · exact d25 (eq_of_mem_of_mem hg1 cb cab3 hL2 hL5)
  · rcases h1 with (hL1 | hL2) | hL4
    · exact d13 (eq_of_mem_of_mem hg1 ca cab hL1 hL3)
    · exact d23 (eq_of_mem_of_mem hg1 cb cab hL2 hL3)
    · exact d34 (eq_of_mem_of_mem hg1 cab cab2 hL3 hL4)

/-- The dimension-3 generalised Beauville structure of `C_p²` (for `p ≥ 5`). -/
def beauville3 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤) (hp2 : p ≠ 2)
    (hp3 : p ≠ 3) : GeneralisedBeauvilleStructure (CpSq p) where
  ι := Fin 3
  pairs := pairs3 hgen hp2 hp3
  inter_sigmaSet_eq_one := inter3_eq_one hgen hp2 hp3

theorem primitive3 {a b : CpSq p} (hgen : Subgroup.closure ({a, b} : Set (CpSq p)) = ⊤)
    (hp2 : p ≠ 2) (hp3 : p ≠ 3) : (beauville3 hgen hp2 hp3).IsPrimitive := by
  intro S hS
  have hex : ∃ j : Fin 3, j ∉ S := by
    by_contra hcon
    simp only [not_exists, not_not] at hcon
    exact hS (Finset.eq_univ_iff_forall.mpr hcon)
  obtain ⟨j, hj⟩ := hex
  obtain ⟨w, hw1, hwi⟩ : ∃ w : CpSq p, w ≠ 1 ∧
      ∀ i : Fin 3, i ≠ j → w ∈ sigmaSet (pairs3 hgen hp2 hp3 i).x (pairs3 hgen hp2 hp3 i).y := by
    fin_cases j
    · refine ⟨a * b ^ 2, mul_pow_ne_one hgen 2, fun i hi => ?_⟩
      fin_cases i
      · exact absurd rfl hi
      · change a * b ^ 2 ∈ sigmaSet a (b ^ 2)
        rw [sigma_d1 hgen hp2]; exact Or.inr (Subgroup.mem_zpowers _)
      · change a * b ^ 2 ∈ sigmaSet (a * b)⁻¹ ((a * b ^ 2) ^ 2)
        rw [sigma_e2 hgen hp2]; exact Or.inl (Or.inr (Subgroup.mem_zpowers _))
    · refine ⟨a * b, mul_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change a * b ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inr (Subgroup.mem_zpowers _)
      · exact absurd rfl hi
      · change a * b ∈ sigmaSet (a * b)⁻¹ ((a * b ^ 2) ^ 2)
        rw [sigma_e2 hgen hp2]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
    · refine ⟨a, fst_ne_one hgen, fun i hi => ?_⟩
      fin_cases i
      · change a ∈ sigmaSet a b
        rw [sigmaSet_of_comm]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · change a ∈ sigmaSet a (b ^ 2)
        rw [sigma_d1 hgen hp2]; exact Or.inl (Or.inl (Subgroup.mem_zpowers _))
      · exact absurd rfl hi
  intro hcontra
  have hwmem : w ∈ ⋂ i ∈ S, sigmaSet ((beauville3 hgen hp2 hp3).pairs i).x
      ((beauville3 hgen hp2 hp3).pairs i).y :=
    Set.mem_iInter₂.mpr (fun i hi => hwi i (fun e => hj (e ▸ hi)))
  rw [hcontra, Set.mem_singleton_iff] at hwmem
  exact hw1 hwmem

/-- **`3 ∈ BSpec(C_p²)`** for primes `p ≥ 5`. -/
theorem three_mem_BSpec (hp2 : p ≠ 2) (hp3 : p ≠ 3) : 3 ∈ BeauvilleSpectrum (CpSq p) :=
  ⟨beauville3 basis_gen hp2 hp3, primitive3 basis_gen hp2 hp3, by
    rw [GeneralisedBeauvilleStructure.dimension]; exact Fintype.card_fin 3⟩

/-- **Corollary.** For odd primes `p`, `BSpec(C_p²) = {4}` if `p = 3` and `{2, 3, 4}` otherwise. -/
theorem BSpec_eq (hp2 : p ≠ 2) :
    BeauvilleSpectrum (CpSq p) = if p = 3 then ({4} : Set ℕ) else {2, 3, 4} := by
  by_cases hp3 : p = 3
  · subst hp3
    rw [if_pos rfl]
    apply Set.eq_of_subset_of_subset
    · intro d hd
      have hle := (isGreatest_BSpec hp2).2 hd
      have hge := (isLeast_BSpec hp2).2 hd
      rw [if_pos rfl] at hge
      simp only [Set.mem_singleton_iff]; omega
    · intro d hd
      simp only [Set.mem_singleton_iff] at hd; subst hd
      exact four_mem_BSpec hp2
  · rw [if_neg hp3]
    apply Set.eq_of_subset_of_subset
    · intro d hd
      have hle := (isGreatest_BSpec hp2).2 hd
      have hge := (isLeast_BSpec hp2).2 hd
      rw [if_neg hp3] at hge
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff]; omega
    · intro d hd
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hd
      rcases hd with rfl | rfl | rfl
      · have h2 := (isLeast_BSpec hp2).1; rwa [if_neg hp3] at h2
      · exact three_mem_BSpec hp2 hp3
      · exact four_mem_BSpec hp2

end CpSq
